# Generated by Django 5.1.2 on 2024-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("ecommerce", "0001_initial"),
        ("ecommerce", "0002_productmodel_description"),
        ("ecommerce", "0003_productmodel_short_description"),
        ("ecommerce", "0004_remove_productmodel_short_description"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("price", models.FloatField()),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
