# Generated by Django 5.1.2 on 2024-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_productmodel_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("PU", "PUBLICADO"),
                    ("BR", "BORRADOR"),
                    ("PR", "PRIVADO"),
                ],
                default="BR",
                max_length=2,
            ),
        ),
    ]
